### ISSUE TITLE
Compiling to native platforms leads to errors, 100$ for fix!

### ISSUE THREAD

**Issue by xoopx** [saharan/OimoPhysics#15]
Compiling to native platforms leads to errors, 100$ for fix!

**Comment by saharan** [comment]
Please give me some more information... Did you use C++ as a platform?

**Comment by xoopx** [comment]
Hi, we need to compile to windows, ios and android natively, using openfl.

**Comment by xoopx** [comment]
Hi, guys,
Any updates about my issue?

**Comment by saharan** [comment]
What error message did you get? It's necessary to identify the cause.

**Comment by McNito** [comment]
Hi,

I've made a new openfl repository (last versions of openfl, haxe, lime) and applied luboslenco fixes for haxe 4 to this repository, and now I've a working html5 3d physics core (working together with Away3D).

The problem is when I try to compile native (example on Android).

![oimophysics](https://user-images.githubusercontent.com/5686581/63090485-b7515280-bf5b-11e9-910e-ff5317498148.png)

Any advice? For any reasons it says "unused import" and fails to compile, but it's working on html5.


Thanks in advance :)

**Comment by saharan** [comment]
This may require a total reconstruction of the library. Will be handled in #46.
