### ISSUE TITLE
Type not found : oimo.common.Mat4 when attempting to build demo's

### ISSUE THREAD

**Issue by nickmcmillan** [saharan/OimoPhysics#16]
I'm attempting to build the demos as per the instructions in the project Readme.

I've installed Haxe Compiler 4.0.0-preview and from the demos folder I've run `haxe -cp src -main demo.js.DemoJS -js index.js`. It returns the following error:

`src/demo/common/DemoBase.hx:4: characters 8-24 : Type not found : oimo.common.Mat4`

I'm new to Haxe so might be missing something obvious. Any help would be appreciated!

**Comment by saharan** [comment]
Hello,

Have you added the main source folder (not demo/src/) to the class path? The demo's source folder is isolated (because it's not necessarily needed) from the main one, so you have to "merge" them somehow. It's accomplished by adding the main source folder to the class path, or merging the two folders directly.

**Comment by nickmcmillan** [comment]
That did the trick. Thanks @saharan.
