### ISSUE TITLE
How can I find out which object I hit with the ray?

### ISSUE THREAD

**Issue by 8Observer8** [saharan/OimoPhysics#59]
I have two platforms and a raw. I need to find out which object I hit with the ray:

![simple-raycasting-oimophysics-webgl-js](https://user-images.githubusercontent.com/3908473/219253807-c0048396-3a75-489b-b8c6-76c18e0930ab.gif)

I tried to find in the [documentaion](https://saharan.github.io/OimoPhysics/) something like `userData` like in Bullet Physics and Box2D to keep names of objects but I didn't find it.

This method works:
```js
    rayCastCallback.process = (shape, hit) => {
        console.log(hit);
    };
```
It prints: fraction, normal and position of hit:
![image](https://user-images.githubusercontent.com/3908473/219254297-1b7de8f7-8591-4a3c-8b46-edc517c03d3f.png)

**Comment by Dev-MarkoF** [comment]
userData is part of the shape associated with the rigidbody. So in your case you won't find it in hit, but in the `shape` like `shape.userData`.
I know it works, since i integrated OIMO into a game engine and heavily rely on this feature to distinguish "Objects" by not only save the name of a body in the user data but a whole "gameObject". 
You can use this shape.userData also in collisionEvents. Be also aware of the fact one body can have multiple shapes attached to them, each shape then has userData.

**Comment by 8Observer8** [comment]
It is better to search in this file: `node_modules\oimophysics\bin\js_modules\OimoPhysics.d.ts`
